AWSTemplateFormatVersion: '2010-09-09'

Description: CFN 101 Workshop - Lab 04 Mapping.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Amazon EC2 Configuration'
        Parameters:
          # Remove InstanceType group.
          - InstanceType
          - AmiID

    ParameterLabels:
      # Remove the InstanceType parameter label.
      InstanceType:
        default: 'Type of EC2 Instance'

      AmiID:
        default: 'Amazon Machine Image ID'

Parameters:
  # Replace the InstanceType parameter with EnvironmentType parameter.
  EnvironmentType:
    Description: 'Specify the Environment type of the stack.'
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - Prod
    ConstraintDescription: 'Specify Dev, Test or Prod.'
  AmiID:
    Type: AWS::EC2::Image::Id
    Description: 'The ID of the AMI.'

# Add a Mappings section here!
Mappings:
  EnvironmentToInstanceType: # Map Name
    Dev: 
      InstanceType: t2.nano
    Test: # Top level key
      InstanceType: t2.micro # Second level key
    Prod:
      InstanceType: t2.small

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref AmiID
      InstanceType: !FindInMap
        - EnvironmentToInstanceType # Map Name
        - !Ref EnvironmentType # Top Level Key
        - InstanceType # Second Level Key
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref EnvironmentType, webserver ] ]
